In [2]:
%matplotlib inline
import pandas as pd
import numpy as np

1. Create a random list of number and then save it to a text file named "simple_data.txt"

In [9]:
import random
rand_list=list(np.random.randint(low = 1,high=100,size=50))

with open('lista_random.txt', mode='w') as f:
    for i in range(len(rand_list)):
        f.write(str(rand_list[i]))
        f.write('\n')

2. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [18]:
matrix_rand = np.random.randint(0,100, size=(5,5))
print(matrix_rand)

with open('matrix_random.txt', mode='w') as f:
    for i in range(matrix_rand.shape[0]):
        f.write(' '.join(map(str, matrix_rand[i])))
        f.write('\n')
        

[[13 79 68 70 20]
 [37  0  6 75 89]
 [50  1 58 70 89]
 [42 13 25 16 96]
 [ 5 96 57 68 27]]


ValueError: I/O operation on closed file.

3. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [14]:
with open("matrix_random.txt", "r") as f:
    data = f.read().replace(" ", ",")
    
    
with open("matrix_random.csv", "w") as g:
    g.write(data)

4. load the binary file named credit_card.dat and convert the data into the real credit-card number. Each line correspond to a credit card number. Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

hint: use the chr() function to convert a number to a char


In [24]:
with open("credit_card.dat", "r") as file:
    file_content=file.read()
    print(len(file_content))
    for line in file_content:
        print(line)
    word_counter=0
    word_size = 6
    
   
        

5955
1
1
0
1
1
1
1
1
0
1
1
0
1
1
0
1
0
0
1
1
1
0
0
0
1
0
0
0
0
0
1
1
0
1
0
1
1
1
0
1
1
0
1
1
0
1
1
1
1
1
0
0
1
1
1
0
0
0
0
0
1
1
0
0
1
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
0
1
0
1
1
0
0
0
0
0
1
1
0
0
1
0
1
1
0
0
1
0
1
1
0
1
1
1
1
1
0
0
0
1
1
0
1
0


1
1
0
0
1
1
1
1
0
0
1
0
1
1
0
1
0
1
1
1
0
1
1
1
1
0
0
0
0
0
1
1
1
0
0
0
1
1
0
0
1
0
1
1
0
1
0
0
1
1
0
1
1
1
1
0
0
0
0
0
1
1
0
0
1
1
1
1
0
0
1
1
1
1
0
1
0
1
1
1
0
1
0
0
1
0
0
0
0
0
1
1
0
0
1
0
1
1
0
0
1
0
1
1
0
1
1
0
1
1
0
1
1
0
1
0
1
0


1
1
0
0
1
0
1
1
0
1
1
1
1
1
0
0
1
0
1
1
0
0
1
0
1
0
0
0
0
0
1
1
0
0
0
0
1
1
0
0
0
0
1
1
0
0
0
0
1
1
0
0
0
1
1
0
0
0
0
0
1
1
0
1
0
0
1
1
0
0
0
0
1
1
0
0
0
1
1
1
0
0
0
1
1
0
0
0
0
0
1
1
0
1
1
0
1
1
0
1
1
0
1
1
0
1
0
1
1
1
0
0
1
0
1
0
1
0


1
1
0
0
0
0
1
1
0
1
1
0
1
1
0
1
1
0
1
1
0
0
0
1
1
0
0
0
0
0
1
1
0
0
1
1
1
1
0
0
0
0
1
1
0
1
1
0
1
1
0
0
1
1
1
0
0
0
0
0
1
1
0
0
1
1
1
1
0
1
1
1
1
1
0
1
0
0
1
1
0
0
1
0
1
0
0
0
0
0
1
1
0
0
1
1
1
1
0
0
0
1
1
1
0
1
0
1
1
1
0
0
0
0
1
0
1
0


1
1
0
0
0
0
1
1
0
1
0
0
1
1
0
0
1
1
1
1
0
0

0b10011101110101
